config/routes.rb
Rails.application.routes.draw do
  resources :boxes
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/box.rb
class Box < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @article = Article.new
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    @article = 'Cueck'
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    debugger
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def handle_record_not_found
      respond_to json: { error: 'you\'re a faggot'}
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title[], :text[])
    end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
    # if !request.headers['Authorization'].nil?
    #   @boxes = Box.all
    # else
    #   render json: { error: 'no auth' }, status: :unauthorized
    # end 
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @article = Article.find(params[:id])
    # rescue ActiveRecord::RecordNotFound
    # render json: { error: 'Baaaaaad'}
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= f.text_field :title %></td>
        <td><%= f.text_field :text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script type="text/javascript">
  $('.submit').click(function(e) {
    e.preventDefault();

    console.log(JSON.stringify($('.form_for').serialize()));
  });  
</script>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/boxes/_form.html.erb
<%= form_for(box) do |f| %>
  <% if box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/destroy.js.erb
$('.btn-destroy').bind('ajax:success', function() {  
  $("tr#box-<%= @box.id %>").fadeOut(500, function(){
    $(this).remove();
  });
});

app/views/boxes/edit.html.erb
<h1>Editing Box</h1>

<%= render 'form', box: @box %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boxes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr id="box-<%= box.id %>">
        <td><%= box.name %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, remote: true, method: :delete, data: { element: box.id }, class: 'btn-destroy' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box', new_box_path %>

<script type="text/javascript">
  // $('.btn-destroy').each(function(index, value) {
  //   $(this).click(function(e) {
  //     e.preventDefault();
  //     e.stopPropagation();
  //     $.ajax({
  //       type: 'POST',
  //       url: `/boxes/${$(this).data('element')}`,
  //       dataType: 'json',
  //       data: {'_method' : 'delete'},
  //       // contentType: 'text/javascript',
  //       success: function(result) {
  //         // console.log(result.id);
  //       }
  //     });
  //   });
  // });
</script>

app/views/boxes/new.html.erb
<h1>New Box</h1>

<%= render 'form', box: @box %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @box.name %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>